version: "3.9"
services:
  euro-football-dashboard-db:
    image: postgres
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_DB_PORT: ${DB_PORT}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "${DB_PORT}:5432"
